import ts from 'typescript';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const root=process.cwd(),tmp=path.join(root,'.sites-runtime/test');fs.mkdirSync(tmp,{recursive:true});
function compile(file,out,change=x=>x){const js=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;fs.writeFileSync(path.join(tmp,out),change(js));}
compile('lib/model.ts','model.mjs');compile('lib/seed.ts','seed.mjs',s=>s.replaceAll("'./model'","'./model.mjs'"));
fs.writeFileSync(path.join(tmp,'mock.mjs'),`import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import path from 'node:path';export const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(name=>name.endsWith('.sql')).sort()) sqlite.exec(fs.readFileSync(path.join('drizzle',file),'utf8'));let user=null;export const setUser=u=>user=u;export const getChatGPTUser=async()=>user;class Query{constructor(sql){this.sql=sql;this.params=[]}bind(...params){this.params=params;return this}async all(){return {results:sqlite.prepare(this.sql).all(...this.params)}}async first(){return sqlite.prepare(this.sql).get(...this.params)||null}async run(){return {meta:sqlite.prepare(this.sql).run(...this.params)}}}export const env={DB:{prepare:sql=>new Query(sql),batch:async statements=>{sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}}};`);
compile('app/api/v1/data/route.ts','route.mjs',s=>s.replace(/import \{ env \} from ['"]cloudflare:workers['"];?/,'').replace(/import \{ getChatGPTUser \} from [^;]+;/,"import {env,getChatGPTUser} from './mock.mjs';").replaceAll("'@/lib/model'","'./model.mjs'").replaceAll("'@/lib/seed'","'./seed.mjs'"));
const {setUser,sqlite}=await import(pathToFileURL(path.join(tmp,'mock.mjs')));const {GET,POST}=await import(pathToFileURL(path.join(tmp,'route.mjs')));
const post=body=>POST(new Request('https://test.local/api/v1/data',{method:'POST',headers:{'Content-Type':'application/json',origin:'https://test.local'},body:JSON.stringify(body)}));
const read=()=>GET(new Request('https://test.local/api/v1/data'));
assert.equal((await read()).status,401);setUser({userId:'A',email:'owner@test.local',displayName:'Owner A'});
assert.equal((await post({action:'seed'})).status,200);let data=await (await read()).json();assert.equal(data.records.filter(r=>r.kind==='students').length,24);
assert.equal(data.organization.id,'org-A');assert.equal(data.role,'owner');assert.equal(data.members.length,1);assert.ok(data.campuses.length>=1);
const group=data.records.find(r=>r.id==='g0');assert.equal((await post({kind:'groups',id:'g0',version:group.version,data:{...group.data,name:'Groupe renommé'}})).status,200);
assert.equal((await post({kind:'students',id:'student-immutable',data:{name:'Élève Identifiant',group:'g0',program:'Programme français',campus:'Béjaïa Centre',guardian:'',phone:'',status:'Actif'}})).status,200);
sqlite.prepare('INSERT INTO records (tenant_id,id,kind,payload,created_at,version) VALUES (?,?,?,?,?,1)').run('org-A','legacy-group','groups',JSON.stringify({name:'Legacy G',program:'Programme français',campus:'Béjaïa Centre',capacity:10}),'legacy');
sqlite.prepare('INSERT INTO records (tenant_id,id,kind,payload,created_at,version) VALUES (?,?,?,?,?,1)').run('org-A','legacy-student','students',JSON.stringify({name:'Ancien Élève',group:'Legacy G',program:'Programme français',campus:'Béjaïa Centre',guardian:'',phone:'',status:'Actif'}),'legacy');
data=await (await read()).json();assert.equal(data.records.find(r=>r.id==='legacy-student').data.group,'Legacy G');
const migrated=await (await post({action:'migrate-legacy'})).json();assert.equal(migrated.unresolvedReferences,0);
data=await (await read()).json();assert.equal(data.records.find(r=>r.id==='legacy-student').data.group,'legacy-group');
const page=await (await GET(new Request('https://test.local/api/v1/data?kind=students&q=Yacine&page=1&pageSize=5'))).json();assert.equal(page.pagination.pageSize,5);assert.ok(page.records.length<=5);assert.ok(page.records.every(r=>r.kind==='students'));
const invited=await (await post({action:'invite',email:'staff@test.local',role:'staff'})).json();assert.ok(invited.token);
assert.notEqual(sqlite.prepare('SELECT token FROM invitations WHERE id=?').get(invited.id).token,invited.token);
setUser({userId:'staff-user',email:'staff@test.local',displayName:'Staff'});
assert.equal((await post({action:'accept-invite',token:invited.token})).status,200);
assert.equal((await post({action:'accept-invite',token:invited.token})).status,400);
data=await (await read()).json();assert.equal(data.organization.id,'org-A');assert.equal(data.role,'staff');assert.ok(data.records.length>0);
setUser({userId:'A',email:'owner@test.local',displayName:'Owner A'});
assert.equal((await post({action:'update-member-role',userId:'staff-user',role:'viewer'})).status,200);
setUser({userId:'staff-user',email:'staff@test.local',displayName:'Staff'});
assert.equal((await post({kind:'announcements',data:{title:'Test',body:'Message',target:'Tous',campus:'Béjaïa Centre'}})).status,403);
assert.equal((await GET(new Request('https://test.local/api/v1/data?backup=1'))).status,403);
setUser({userId:'A',email:'owner@test.local',displayName:'Owner A'});
const backup=await (await GET(new Request('https://test.local/api/v1/data?backup=1'))).json();assert.equal(backup.organization.id,'org-A');assert.ok(backup.records.length>0);
assert.equal((await post({action:'seed'})).status,409);
const selfInvite=await (await post({action:'invite',email:'owner@test.local',role:'viewer'})).json();
assert.equal((await post({action:'accept-invite',token:selfInvite.token})).status,200);
assert.equal((await (await read()).json()).role,'owner');
const expired=await (await post({action:'invite',email:'expired@test.local',role:'staff'})).json();
sqlite.prepare('UPDATE invitations SET expires_at=? WHERE id=?').run('2000-01-01T00:00:00.000Z',expired.id);
setUser({userId:'exp-user',email:'expired@test.local',displayName:'Expired'});
assert.equal((await post({action:'accept-invite',token:expired.token})).status,400);
setUser({userId:'A',email:'owner@test.local',displayName:'Owner A'});
const revoked=await (await post({action:'invite',email:'revoked@test.local',role:'staff'})).json();
assert.equal((await post({action:'revoke-invite',id:revoked.id})).status,200);
setUser({userId:'rev-user',email:'revoked@test.local',displayName:'Revoked'});
assert.equal((await post({action:'accept-invite',token:revoked.token})).status,400);
setUser({userId:'A',email:'owner@test.local',displayName:'Owner A'});
assert.equal((await post({action:'update-member-role',userId:'staff-user',role:'admin'})).status,200);
setUser({userId:'staff-user',email:'staff@test.local',displayName:'Staff'});
assert.equal((await post({action:'update-member-role',userId:'A',role:'viewer'})).status,403);
assert.equal((await post({action:'update-member-role',userId:'staff-user',role:'owner'})).status,403);
setUser({userId:'A',email:'owner@test.local',displayName:'Owner A'});
assert.equal((await post({action:'update-member-role',userId:'A',role:'admin'})).status,403);
assert.equal((await post({action:'update-member-role',userId:'staff-user',role:'viewer'})).status,200);
setUser({userId:'B',email:'other@test.local',displayName:'Other B'});assert.equal((await (await read()).json()).records.length,0);
assert.equal((await post({kind:'payments',data:{student:'s1',invoice:'i1',amount:1,date:'2026-09-18',method:'Espèces',campus:'Béjaïa Centre'}})).status,400);
setUser({userId:'A',email:'owner@test.local',displayName:'Owner A'});
const payment={student:'s1',invoice:'i1',amount:7000,date:'2026-09-18',method:'Espèces',campus:'Béjaïa Centre'};
assert.equal((await post({kind:'payments',id:'payment-one',data:payment})).status,200);
assert.equal((await post({kind:'payments',id:'payment-two',data:payment})).status,400);
assert.equal((await post({kind:'payments',id:'payment-one',data:{...payment,amount:10}})).status,400);
assert.equal((await post({kind:'payments',id:'payment-three',data:{...payment,amount:5000}})).status,200);
const student=data.records.find(r=>r.id==='s1');assert.equal((await post({kind:'students',id:'s1',version:1,data:{...student.data,name:'Yacine Test'}})).status,200);
assert.equal((await post({kind:'students',id:'s1',version:1,data:student.data})).status,409);
const session=data.records.find(r=>r.kind==='sessions');assert.equal((await post({kind:'sessions',data:session.data})).status,409);
assert.equal((await post({kind:'grades',data:{student:'s1',subject:'Maths',title:'Test',score:21,scale:20,coefficient:1,source:'INTERNAL',campus:'Béjaïa Centre'}})).status,400);
assert.equal((await post({kind:'attendance',data:{student:'s0',session:'se21-0',status:'Présent',campus:'Béjaïa Centre'}})).status,200);
const a=(await (await read()).json()).records.find(r=>r.kind==='attendance');assert.equal(a.data.status,'Présent');
assert.equal((await post({kind:'attendance',id:a.id,version:a.version,data:{...a.data,status:'Absent'}})).status,200);
assert.equal((await (await read()).json()).records.find(r=>r.id===a.id).data.status,'Absent');
assert.ok((await (await read()).json()).audit.length>=5);
assert.equal((await POST(new Request('https://test.local/api/v1/data',{method:'POST',body:'{}'}))).status,403);
assert.equal((await POST(new Request('https://test.local/api/v1/data',{method:'POST',headers:{origin:'https://evil.test'},body:'{}'}))).status,403);
console.log('PASS: 46 API checks — authentication, organisations, RBAC, invitations (expiration, révocation, jeton haché, usage unique), protection des owners, migration legacy explicite, tenant isolation, pagination, demo seed, references, payments, optimistic locking, schedule conflicts, grades, attendance, audit and CSRF.');
