'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {LayoutDashboard,Users,GraduationCap,CalendarDays,ClipboardCheck,BookOpen,Wallet,Globe,UserPlus,Settings,ArrowUpRight,Plus,Search,Bell,ChevronRight,Download,Clock,FileText,MessageSquare,ShieldCheck,Layers,RefreshCw,HelpCircle,School,type LucideIcon} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster,toast} from 'sonner';
import {Kind,RecordRow,money,programs,today} from '@/lib/model';
import {demoRecords} from '@/lib/seed';
import {currentSchoolYear,initials,weekDates} from '@/lib/display';
import {Pick,Pill} from '@/components/workspace/primitives';
import {SettingsView} from '@/components/workspace/settings';
import {RecordFields} from '@/components/workspace/record-fields';
import {AnnouncementsView,GroupsView,HomeworkView,LeadsView,StudentsView,TeachersView} from '@/components/workspace/records';
import {FinanceView} from '@/components/workspace/finance';
import {CnedView} from '@/components/workspace/cned';
import {AttendanceView,GradesView,SessionsView} from '@/components/workspace/schedule';
import {DashboardView} from '@/components/workspace/dashboard';
import {OnboardingWizard} from '@/components/workspace/onboarding';
import {downloadBackup,errorMessage,inviteMember,loadWorkspace,seedWorkspace,updateMemberRole,writeRecord,type AuditEntry,type InvitationSummary,type MemberSummary,type OrganizationSummary,type Role,type SchoolYearSummary,type UserSummary} from '@/lib/workspace-api';
const nav=[['dashboard','Vue d’ensemble',LayoutDashboard],['students','Élèves',Users],['groups','Classes & groupes',Layers],['teachers','Enseignants',GraduationCap],['sessions','Emploi du temps',CalendarDays],['attendance','Présences',ClipboardCheck],['grades','Notes & évaluations',BookOpen],['homework','Cahier de textes',FileText],['cned','Suivi CNED',Globe],['finance','Finances',Wallet],['leads','Admissions',UserPlus],['announcements','Annonces',MessageSquare],['settings','Paramètres',Settings]] as const;
const labels:Record<string,string>={students:'un élève',groups:'un groupe',teachers:'un enseignant',sessions:'une séance',grades:'une note',homework:'un devoir',cned:'un devoir CNED',invoices:'une échéance',payments:'un paiement',leads:'un prospect',announcements:'une annonce'};
type ModelContext={registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown};

export default function Workspace({demo=false}:{demo?:boolean}){
 const [rawView,setView]=useState('dashboard'),[rows,setRows]=useState<RecordRow[]>(demo?demoRecords():[]),[audit,setAudit]=useState<AuditEntry[]>([]),[loading,setLoading]=useState(!demo),[error,setError]=useState(''),[campus,setCampus]=useState('Tous les campus'),[query,setQuery]=useState(''),[filter,setFilter]=useState('Tous'),[date,setDate]=useState(()=>demo?'2026-09-21':today()),[selectedSession,setSelectedSession]=useState(''),[modal,setModal]=useState<Kind|null>(null),[editing,setEditing]=useState<RecordRow|null>(null),[form,setForm]=useState<Record<string,unknown>>({}),[busy,setBusy]=useState(false),[detail,setDetail]=useState<RecordRow<'students'>|null>(null),[help,setHelp]=useState(false),[onboard,setOnboard]=useState(false),[receipt,setReceipt]=useState<RecordRow<'payments'>|null>(null);
 const [mutationId,setMutationId]=useState(''),[user,setUser]=useState<UserSummary>({displayName:'Direction',email:''}),[organization,setOrganization]=useState<OrganizationSummary>({id:'',name:'Mon établissement'}),[role,setRole]=useState<Role>('viewer'),[members,setMembers]=useState<MemberSummary[]>([]),[invitations,setInvitations]=useState<InvitationSummary[]>([]),[schoolYears,setSchoolYears]=useState<SchoolYearSummary[]>([]);
 const list=<K extends Kind>(kind:K)=>rows.filter(r=>r.kind===kind&&(campus==='Tous les campus'||kind==='settings'||('campus' in r.data&&r.data.campus===campus))) as RecordRow<K>[];
 const settings=list('settings')[0]?.data||{name:'Mon établissement',year:currentSchoolYear(),cned:true,finance:true,admissions:true};
 const availableCampuses=[...new Set(rows.flatMap(r=>'campus' in r.data?[r.data.campus]:[]))];
 const campusOptions=availableCampuses.length?availableCampuses:['Campus principal'];
 const selectedWeek=weekDates(date),userFirstName=user.displayName.split(/[\s@]/)[0]||'Direction',userInitials=initials(user.displayName||user.email||'Direction');
 const studentName=(id:string)=>list('students').find(r=>r.id===id)?.data.name||'Élève inconnu';
 const groupName=(id:string)=>list('groups').find(r=>r.id===id)?.data.name||'Groupe inconnu';
 const teacherName=(id:string)=>list('teachers').find(r=>r.id===id)?.data.name||'Enseignant inconnu';
 const isScoped=role==='student'||role==='guardian';
 const view=isScoped?'cned':rawView;
 const load=useCallback(async()=>{if(demo)return;setError('');try{const snapshot=await loadWorkspace();setRows(snapshot.records);setAudit(snapshot.audit);setUser(snapshot.user);setOrganization(snapshot.organization);setRole(snapshot.role);setMembers(snapshot.members);setInvitations(snapshot.invitations);setSchoolYears(snapshot.schoolYears);}catch(error:unknown){setError(errorMessage(error));}finally{setLoading(false)}},[demo]);
 useEffect(()=>{queueMicrotask(load)},[load]);
 const go=useCallback((v:string)=>{if(isScoped&&v!=='cned')return;setView(v);setQuery('');setFilter('Tous')},[isScoped]);
 useEffect(()=>{const ctx=(document as Document&{modelContext?:ModelContext}).modelContext;if(!ctx)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:'open_eylite_module',description:'Ouvre un module Eylite sans modifier les données.',inputSchema:{type:'object',properties:{module:{type:'string',enum:nav.map(n=>n[0])}},required:['module'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||!('module' in input)||typeof input.module!=='string'||!nav.some(n=>n[0]===input.module))throw new Error('Module inconnu');go(input.module);return {module:input.module}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[go]);
 async function write(kind:Kind,data:unknown,id?:string,version?:number){if(demo)throw new Error('La visite est en lecture seule. Ouvrez votre espace privé pour enregistrer.');const result=await writeRecord(kind,data,id,version);await load();return result;}
 function open(kind:Kind,row?:RecordRow){setMutationId(crypto.randomUUID());setEditing(row||null);setForm(row?.data||{campus:campus==='Tous les campus'?campusOptions[0]:campus,program:programs[0],group:list('groups')[0]?.id||'',student:list('students')[0]?.id||'',status:kind==='cned'?'À faire':kind==='leads'?'Prospect':'Actif',date,source:kind==='leads'?'Téléphone':'INTERNAL',method:'Espèces',formula:'Classe complète réglementée',scale:20,coefficient:1,capacity:25,target:'Tous',score:'',start:'08:00',end:'10:00'});setModal(kind)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);try{await write(modal,form,editing?.id||mutationId,editing?.version);setModal(null);toast.success('Enregistrement effectué');}catch(error:unknown){toast.error(errorMessage(error))}finally{setBusy(false)}}
 async function seed(){setBusy(true);try{await seedWorkspace();await load();toast.success('Données fictives chargées')}catch(error:unknown){toast.error(errorMessage(error))}finally{setBusy(false)}}
 const paid=(id:string)=>list('payments').filter(r=>r.data.invoice===id).reduce((s,r)=>s+r.data.amount,0);
 const invoices=list('invoices'),payments=list('payments'),outstanding=invoices.filter(r=>paid(r.id)<r.data.amount),overdue=outstanding.filter(r=>r.data.due<today());
 const totalPaid=payments.reduce((s,r)=>s+r.data.amount,0),totalDue=outstanding.reduce((s,r)=>s+r.data.amount-paid(r.id),0),students=list('students').filter(r=>r.data.status==='Actif');
 const sessions=list('sessions').filter(r=>r.data.date===date).sort((a,b)=>a.data.start.localeCompare(b.data.start));
 const currentSession=sessions.find(r=>r.id===selectedSession)||sessions[0];const classStudents=students.filter(r=>r.data.group===currentSession?.data.group);
 const activeAttendance=list('attendance').filter(r=>sessions.some(s=>s.id===r.data.session));const absent=activeAttendance.filter(r=>r.data.status==='Absent').length;
 const cnedLate=list('cned').filter(r=>r.data.due<today()&&!['Envoyé','Correction en attente','Corrigé'].includes(r.data.status));
 function exportCSV(){const kind:Kind=view==='finance'?'invoices':view as Kind;const data=list(kind);if(!data.length){toast.info('Aucune donnée à exporter');return}const keys=Object.keys(data[0].data);const esc=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const csv='\uFEFF'+[['id',...keys].map(esc).join(';'),...data.map(r=>[r.id,...keys.map(k=>Reflect.get(r.data,k))].map(esc).join(';'))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='eylite-'+kind+'.csv';a.click();URL.revokeObjectURL(a.href)}
 const searched=<K extends Kind>(kind:K)=>list(kind).filter(r=>JSON.stringify(r.data).toLowerCase().includes(query.toLowerCase())&&(filter==='Tous'||('program' in r.data&&r.data.program===filter)||('group' in r.data&&r.data.group===filter)||('source' in r.data&&r.data.source===filter)));
 const title=nav.find(n=>n[0]===view)?.[1]||'Eylite';
 const dashboardStats:[string,string|number,string,LucideIcon,string][]= [["Élèves actifs",students.length,'Tous programmes confondus',Users,'green'],['Présences renseignées',activeAttendance.length,absent+' absence(s) enregistrée(s)',ClipboardCheck,'blue'],['Encaissements',money(totalPaid),'Paiements enregistrés',Wallet,'orange'],['Solde à recevoir',money(totalDue),overdue.length+' échéances en retard',Clock,'purple']];
 const tools=<div className="tools"><div className="search-box"><Search size={17}/><input aria-label="Rechercher" placeholder="Rechercher…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{['students','groups','leads'].includes(view)&&<Pick value={filter} onChange={setFilter} options={['Tous',...programs]} label="Programme"/>}<button className="button secondary" onClick={exportCSV}><Download size={16}/>Exporter CSV</button></div>;
 return <SidebarProvider><Toaster richColors position="top-right"/><Sidebar className="eylite-sidebar"><SidebarHeader><div className="brand"><span className="brand-mark">e</span>eylite<span className="brand-dot">.</span></div><div className="organization"><span className="org-icon"><School size={20}/></span><div><strong>{settings.name}</strong><small>{isScoped?(role==='student'?'Espace élève':'Espace parent'):'Espace direction'}</small></div></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>PILOTAGE & SCOLARITÉ</SidebarGroupLabel><SidebarMenu>{nav.filter(n=>n[0]!=='settings'&&(n[0]!=='cned'||settings.cned)&&(n[0]!=='finance'||settings.finance)&&(n[0]!=='leads'||settings.admissions)&&(!isScoped||n[0]==='cned')).map(([id,label,Icon],i)=><SidebarMenuItem key={id}>{i===9&&!isScoped&&<div className="nav-divider">ADMINISTRATION</div>}<SidebarMenuButton isActive={view===id} onClick={()=>go(id)}><Icon/><span>{isScoped&&id==='cned'?'Mon suivi':label}</span>{id==='cned'&&cnedLate.length>0&&<span className="nav-count">{cnedLate.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter>{!isScoped&&(role==='owner'||role==='admin')&&<button className="nav-bottom" onClick={()=>setOnboard(true)}><School size={18}/>Assistant de démarrage</button>}<button className="nav-bottom" onClick={()=>setHelp(true)}><HelpCircle size={18}/>Centre d’aide</button>{!isScoped&&<button className={'nav-bottom '+(view==='settings'?'selected':'')} onClick={()=>go('settings')}><Settings size={18}/>Paramètres</button>}<div className="profile"><div className="avatar dark">{userInitials}</div><div><strong>{user.displayName}</strong><small>{role==='owner'||role==='admin'?'Administrateur de l’espace':role==='staff'?'Équipe pédagogique':role==='student'?'Élève':role==='guardian'?'Parent / responsable':'Lecture seule'}</small></div><ShieldCheck size={17}/></div></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>{isScoped?'Espace personnel':'Espace direction'}</span><ChevronRight size={14}/><b>{isScoped?'Mon suivi CNED':title}</b></div><div className="top-actions"><span className="year"><CalendarDays size={15}/>{settings.year}</span><button aria-label="Voir les annonces" className="icon-btn" onClick={()=>go('announcements')}><Bell size={19}/></button><span className="avatar small">{userInitials}</span></div></header>
 <div className="page"><div className="page-heading"><div><div className="eyebrow">{view==='dashboard'?'VOTRE ÉTABLISSEMENT, EN UN REGARD':settings.name.toUpperCase()+' · '+settings.year}</div><h1>{view==='dashboard'?`Bonjour, ${userFirstName}`:title}{view==='dashboard'&&<span className="hello"> ☀</span>}</h1><p>{view==='dashboard'?'Une nouvelle journée pour faire grandir les talents.':view==='cned'?'Suivez chaque devoir, de sa préparation à sa correction.':view==='finance'?'Échéances, encaissements et suivi des familles.':view==='students'?'Tous les parcours, un dossier unique par élève.':view==='attendance'?'Un appel simple, pour ne perdre personne de vue.':'Retrouvez et gérez les informations de votre établissement.'}</p></div><div className="heading-actions">{!isScoped&&<><Pick value={campus} onChange={setCampus} options={['Tous les campus',...campusOptions]} label="Campus"/>{labels[view]&&<button className="button primary" onClick={()=>open(view as Kind)}><Plus size={17}/>Ajouter {labels[view]}</button>}{view==='dashboard'&&<button className="button primary" onClick={()=>open('students')}><Plus size={17}/>Inscrire un élève</button>}</>}</div></div>
 <div className="demo-strip"><span><span className="demo-label">VERSION PILOTE</span> {demo?'Visite en lecture seule · données fictives':'Espace privé · données de démonstration fictives'}</span>{demo&&<Link href="/">Ouvrir mon espace privé →</Link>}<button onClick={()=>setHelp(true)}>Périmètre de cette version <ArrowUpRight size={14}/></button></div>
 {loading?<div className="empty"><RefreshCw className="spin"/><h2>Ouverture de votre établissement…</h2></div>:error?<div className="empty"><h2>{error}</h2><button className="button" onClick={load}>Réessayer</button><a href="/login" target="_top">Se connecter</a><a href="/demo">Visiter la démonstration en lecture seule</a></div>:rows.length===0&&!isScoped?<div className="empty"><School size={42}/><h2>Bienvenue dans Eylite</h2><a href="/demo">Visiter la démonstration en lecture seule</a><p>Découvrez les parcours avec une école fictive ou créez votre premier élève.</p><button className="button primary" onClick={()=>setOnboard(true)}>Assistant de démarrage guidé</button><button className="button secondary" disabled={busy} onClick={seed}>Charger l’établissement de démonstration</button><button className="button secondary" onClick={()=>open('students')}>Commencer un espace vide</button></div>:<>
 {view==='dashboard'&&<DashboardView stats={dashboardStats} sessions={sessions} date={date} selectedWeek={selectedWeek} overdue={overdue} cnedLate={cnedLate} pendingLeads={list('leads').filter(r=>r.data.status!=='Inscrit').length} students={students} payments={payments} studentName={studentName} groupName={groupName} teacherName={teacherName} setDate={setDate} onCall={session=>{setSelectedSession(session.id);go('attendance')}} onNavigate={go} onReceipt={setReceipt}/>}
 {view==='students'&&<StudentsView rows={searched('students')} tools={tools} groupName={groupName} onDetail={setDetail} onEdit={row=>open('students',row)}/>}
 {view==='groups'&&<GroupsView rows={searched('groups')} students={students} tools={tools} onEdit={row=>open('groups',row)}/>}
 {view==='teachers'&&<TeachersView rows={searched('teachers')} tools={tools} onEdit={row=>open('teachers',row)}/>}
 {view==='sessions'&&<SessionsView rows={sessions} date={date} setDate={setDate} groupName={groupName} teacherName={teacherName} onEdit={row=>open('sessions',row)} onCall={row=>{setSelectedSession(row.id);go('attendance')}}/>}
 {view==='attendance'&&<AttendanceView sessions={sessions} currentSession={currentSession} students={classStudents} attendance={list('attendance')} groupName={groupName} date={date} setDate={setDate} setSelectedSession={setSelectedSession} onStatus={async(student,current,status)=>{try{await write('attendance',{student:student.id,session:currentSession?.id,status,campus:student.data.campus},current?.id,current?.version);toast.success('Présence enregistrée')}catch(error:unknown){toast.error(errorMessage(error))}}}/>}
 {view==='grades'&&<GradesView rows={searched('grades')} filter={filter} setFilter={setFilter} studentName={studentName} onEdit={row=>open('grades',row)}/>}
 {view==='homework'&&<HomeworkView rows={searched('homework')} tools={tools} groupName={groupName} onEdit={row=>open('homework',row)}/>}
 {view==='cned'&&<CnedView demo={demo} rows={list('cned')} late={cnedLate} studentName={studentName} onEdit={row=>open('cned',row)} role={role} schoolYears={schoolYears}/>}
 {view==='finance'&&<FinanceView invoices={invoices} payments={payments} outstanding={outstanding} overdue={overdue} totalPaid={totalPaid} totalDue={totalDue} studentName={studentName} onNew={kind=>open(kind)} onCollect={invoice=>{open('payments');setForm({student:invoice.data.student,invoice:invoice.id,amount:invoice.data.amount-paid(invoice.id),method:'Espèces',date:today(),campus:invoice.data.campus})}} onReceipt={setReceipt}/>}
 {view==='leads'&&<LeadsView rows={searched('leads')} tools={tools} onEdit={row=>open('leads',row)}/>}
 {view==='announcements'&&<AnnouncementsView rows={list('announcements')} onEdit={row=>open('announcements',row)}/>}
 {view==='settings'&&<SettingsView settings={settings} audit={audit} organization={organization} role={role} members={members} invitations={invitations} onUpdate={async data=>write('settings',data,list('settings')[0]?.id,list('settings')[0]?.version)} onInvite={async(email,memberRole,linkStudentId,linkGuardianId)=>{const result=await inviteMember(email,memberRole,linkStudentId,linkGuardianId);toast.success(result.token?`Invitation créée · code ${result.token}`:'Invitation créée');await load()}} onRole={async(userId,memberRole)=>{await updateMemberRole(userId,memberRole);await load()}} onBackup={downloadBackup}/>}
 </>}
 <footer className="page-footer"><span>eylite. <span>Une seule plateforme, plusieurs façons d’enseigner.</span></span><span><ShieldCheck size={14}/>Espace privé</span></footer></div></main>
 <Dialog open={!!modal} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="form-dialog"><DialogTitle>{editing?'Modifier':'Ajouter'} {modal?labels[modal]:''}</DialogTitle><DialogDescription>Les informations sont enregistrées dans votre établissement.</DialogDescription><form onSubmit={submit} className="record-form">{modal&&<RecordFields kind={modal} form={form} set={(key,value)=>setForm(current=>({...current,[key]:value}))} rows={rows}/>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Annuler</button><button className="button primary" disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}</button></div></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><DialogContent><DialogTitle>{detail?.data.name}</DialogTitle><DialogDescription>Dossier élève · EYL-{detail?.id.slice(0,8).toUpperCase()}</DialogDescription>{detail&&<div className="student-detail"><Pill>{detail.data.status}</Pill><p><b>Parcours :</b> {detail.data.program} · {groupName(detail.data.group)}</p><p><b>Campus :</b> {detail.data.campus}</p><p><b>Responsable :</b> {detail.data.guardian||'Non renseigné'}</p><p><b>Téléphone :</b> {detail.data.phone||'Non renseigné'}</p><hr/><h3>Résultats internes</h3><p>{(()=>{const g=list('grades').filter(r=>r.data.student===detail.id&&r.data.source==='INTERNAL');return g.length?(g.reduce((s,r)=>s+r.data.score/r.data.scale*20*r.data.coefficient,0)/g.reduce((s,r)=>s+r.data.coefficient,0)).toFixed(2)+' / 20 (moyenne pondérée)':'Aucune note interne'})()}</p><h3>Suivi financier</h3><p>Solde : {money(list('invoices').filter(r=>r.data.student===detail.id).reduce((s,r)=>s+r.data.amount-paid(r.id),0))}</p><button className="button primary" onClick={()=>{open('students',detail);setDetail(null)}}>Modifier le dossier</button></div>}</DialogContent></Dialog>
 <Dialog open={!!receipt} onOpenChange={o=>!o&&setReceipt(null)}><DialogContent className="receipt-dialog"><DialogTitle>Reçu de paiement</DialogTitle><DialogDescription>Justificatif interne de règlement</DialogDescription>{receipt&&<div className="receipt"><div className="brand">eylite.</div><h2>{settings.name}</h2><small>N° EYL-{receipt.id.toUpperCase()}</small><hr/><p>Reçu de : <strong>{studentName(receipt.data.student)}</strong></p><p>Le {receipt.data.date} · {receipt.data.method}</p><div className="receipt-amount">{money(receipt.data.amount)}</div><p>{list('invoices').find(r=>r.id===receipt.data.invoice)?.data.label}</p><p>{receipt.data.campus} · Caisse direction</p><hr/><p>Paiement enregistré. Merci pour votre confiance.</p><button className="button primary" onClick={()=>window.print()}><Download size={17}/>Imprimer / enregistrer en PDF</button></div>}</DialogContent></Dialog>
 <OnboardingWizard open={onboard} onClose={()=>setOnboard(false)} schoolYears={schoolYears} onDone={load}/>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogTitle>Bienvenue dans Eylite</DialogTitle><DialogDescription>Une première version fonctionnelle pour tester votre organisation.</DialogDescription><div className="help-content"><h3>Ce que vous pouvez faire</h3><p>Créer et modifier les élèves, groupes et enseignants, programmer des séances, faire l’appel, enregistrer des notes, suivre les devoirs CNED, gérer les échéances, encaisser et imprimer les reçus.</p><h3>Vos données</h3><p>Les changements sont sauvegardés côté serveur dans un espace privé associé à votre compte. Les exemples sont fictifs.</p><h3>Avant une ouverture aux écoles</h3><p>Les comptes parents et professeurs, rôles partagés, imports Excel, fichiers joints, arabe, mode hors connexion et intégrations SMS, paiement et IA restent à développer. Cette version pilote ne constitue pas encore la version commerciale complète du cahier des charges.</p></div></DialogContent></Dialog>
 </SidebarProvider>
}

